package GUI;

import Program.ControlClass;
import Program.Util.OpenFile;
import Program.Validation.Validates;
import java.awt.Toolkit;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.w3c.dom.Document;

//This class implements the application's main window
public class MainWindow extends javax.swing.JFrame {

    //Attributes
    private int selectedFunction;
    private final ControlClass controlClass;
    private Document docXml;
    private String xsdFileName;

    //Constructor
    public MainWindow(ControlClass controlClass) {
        this.controlClass = controlClass;
        this.selectedFunction = 0;
        this.setLookAndFeel();
        this.initComponents();
        this.setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_Functions = new javax.swing.ButtonGroup();
        buttonGroup_Proofs = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel_StartScreen = new javax.swing.JPanel();
        jLabel_Logo = new javax.swing.JLabel();
        jLabel_ClickToStart = new javax.swing.JLabel();
        jLabel_VersionName = new javax.swing.JLabel();
        jPanel_ProgramPanel = new javax.swing.JPanel();
        jPanel_Stripe1 = new javax.swing.JPanel();
        jLabel_Title = new javax.swing.JLabel();
        jPanel_Stripe6 = new javax.swing.JPanel();
        jPanel_LoadModel = new javax.swing.JPanel();
        jTextField_ModelFile = new javax.swing.JTextField();
        jLabel_ModelFile = new javax.swing.JLabel();
        jButton_LoadModel = new javax.swing.JButton();
        jLabel_LoadFileOutput = new javax.swing.JLabel();
        jPanel_Functions = new javax.swing.JPanel();
        jRadioButton_ModelCheck = new javax.swing.JRadioButton();
        jRadioButton_IndividualSatisfiesConstraint = new javax.swing.JRadioButton();
        jRadioButton_ListTagValues = new javax.swing.JRadioButton();
        jRadioButton_ListIndividualTags = new javax.swing.JRadioButton();
        jRadioButton_ListIndividualsByConstraint = new javax.swing.JRadioButton();
        jRadioButton_ListIndividualHierarchy = new javax.swing.JRadioButton();
        jPanel_Parameters = new javax.swing.JPanel();
        jTextField_ConstraintTag1 = new javax.swing.JTextField();
        jLabel_RequiredTag = new javax.swing.JLabel();
        jLabel_RequiredTagValue = new javax.swing.JLabel();
        jTextField_ConstraintValue1 = new javax.swing.JTextField();
        jLabel_TargetTag = new javax.swing.JLabel();
        jTextField_ConstraintTag2 = new javax.swing.JTextField();
        jLabel_TargetTagValue = new javax.swing.JLabel();
        jTextField_ConstraintValue2 = new javax.swing.JTextField();
        jLabel_IndividualID = new javax.swing.JLabel();
        jTextField_IndividualID = new javax.swing.JTextField();
        jLabel_TargetTag1 = new javax.swing.JLabel();
        jTextField_TargetTag = new javax.swing.JTextField();
        jLabel_RequiredTagValue1 = new javax.swing.JLabel();
        jTextField_IndividualIdTag = new javax.swing.JTextField();
        jPanel_Description = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Description = new javax.swing.JTextArea();
        jButton_Run = new javax.swing.JButton();
        jPanel_Results = new javax.swing.JPanel();
        jScrollPane_Results = new javax.swing.JScrollPane();
        jTextArea_Results = new javax.swing.JTextArea();
        jPanel_Proofs = new javax.swing.JPanel();
        jRadioButton_Proof1a = new javax.swing.JRadioButton();
        jRadioButton_Proof1b = new javax.swing.JRadioButton();
        jRadioButton_Proof2 = new javax.swing.JRadioButton();
        jRadioButton_Proof3a = new javax.swing.JRadioButton();
        jRadioButton_Proof3b = new javax.swing.JRadioButton();
        jRadioButton_Proof4 = new javax.swing.JRadioButton();
        jRadioButton_Proof5 = new javax.swing.JRadioButton();
        jRadioButton_Proof6a = new javax.swing.JRadioButton();
        jRadioButton_Proof6b = new javax.swing.JRadioButton();
        jCheckBox_ActivateProofs = new javax.swing.JCheckBox();
        jPanel_ProofTitle = new javax.swing.JPanel();
        jLabel_ProofTitle = new javax.swing.JLabel();

        buttonGroup_Functions.add(jRadioButton_IndividualSatisfiesConstraint);
        buttonGroup_Functions.add(jRadioButton_ListIndividualHierarchy);
        buttonGroup_Functions.add(jRadioButton_ListIndividualTags);
        buttonGroup_Functions.add(jRadioButton_ListTagValues);
        buttonGroup_Functions.add(jRadioButton_ListIndividualsByConstraint);
        buttonGroup_Functions.add(jRadioButton_ModelCheck);

        buttonGroup_Proofs.add(jRadioButton_Proof1a);
        buttonGroup_Proofs.add(jRadioButton_Proof1b);
        buttonGroup_Proofs.add(jRadioButton_Proof2);
        buttonGroup_Proofs.add(jRadioButton_Proof3a);
        buttonGroup_Proofs.add(jRadioButton_Proof3b);
        buttonGroup_Proofs.add(jRadioButton_Proof3a);
        buttonGroup_Proofs.add(jRadioButton_Proof3b);
        buttonGroup_Proofs.add(jRadioButton_Proof4);
        buttonGroup_Proofs.add(jRadioButton_Proof5);
        buttonGroup_Proofs.add(jRadioButton_Proof6a);
        buttonGroup_Proofs.add(jRadioButton_Proof6b);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TERMINUS - XML");
        setName("janelaPrograma"); // NOI18N

        jLabel_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/terminus_xml_big.png"))); // NOI18N
        jLabel_Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_LogoMouseClicked(evt);
            }
        });

        jLabel_ClickToStart.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_ClickToStart.setText("Clique para iniciar");

        jLabel_VersionName.setFont(new java.awt.Font("Trebuchet MS", 2, 24)); // NOI18N
        jLabel_VersionName.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_VersionName.setText("XML");

        javax.swing.GroupLayout jPanel_StartScreenLayout = new javax.swing.GroupLayout(jPanel_StartScreen);
        jPanel_StartScreen.setLayout(jPanel_StartScreenLayout);
        jPanel_StartScreenLayout.setHorizontalGroup(
            jPanel_StartScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel_StartScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_StartScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_ClickToStart)
                    .addComponent(jLabel_VersionName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_StartScreenLayout.setVerticalGroup(
            jPanel_StartScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_StartScreenLayout.createSequentialGroup()
                .addComponent(jLabel_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_VersionName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_ClickToStart, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Stripe1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel_Stripe1.setForeground(new java.awt.Color(51, 204, 0));

        javax.swing.GroupLayout jPanel_Stripe1Layout = new javax.swing.GroupLayout(jPanel_Stripe1);
        jPanel_Stripe1.setLayout(jPanel_Stripe1Layout);
        jPanel_Stripe1Layout.setHorizontalGroup(
            jPanel_Stripe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel_Stripe1Layout.setVerticalGroup(
            jPanel_Stripe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jLabel_Title.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel_Title.setText("Terminus - Versão XML");

        jPanel_Stripe6.setBackground(new java.awt.Color(204, 0, 0));
        jPanel_Stripe6.setForeground(new java.awt.Color(51, 204, 0));

        javax.swing.GroupLayout jPanel_Stripe6Layout = new javax.swing.GroupLayout(jPanel_Stripe6);
        jPanel_Stripe6.setLayout(jPanel_Stripe6Layout);
        jPanel_Stripe6Layout.setHorizontalGroup(
            jPanel_Stripe6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_Stripe6Layout.setVerticalGroup(
            jPanel_Stripe6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel_LoadModel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Carregar Modelo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N

        jLabel_ModelFile.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel_ModelFile.setText("Arquivo do Modelo:");

        jButton_LoadModel.setText("Carregar");
        jButton_LoadModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoadModelActionPerformed(evt);
            }
        });

        jLabel_LoadFileOutput.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel_LoadModelLayout = new javax.swing.GroupLayout(jPanel_LoadModel);
        jPanel_LoadModel.setLayout(jPanel_LoadModelLayout);
        jPanel_LoadModelLayout.setHorizontalGroup(
            jPanel_LoadModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LoadModelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_ModelFile, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_ModelFile, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_LoadModel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_LoadFileOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );
        jPanel_LoadModelLayout.setVerticalGroup(
            jPanel_LoadModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LoadModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel_ModelFile)
                .addComponent(jTextField_ModelFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton_LoadModel))
            .addComponent(jLabel_LoadFileOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel_Functions.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Funções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N

        jRadioButton_ModelCheck.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jRadioButton_ModelCheck.setText("Verificar Modelo");
        jRadioButton_ModelCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ModelCheckActionPerformed(evt);
            }
        });

        jRadioButton_IndividualSatisfiesConstraint.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jRadioButton_IndividualSatisfiesConstraint.setText("Indivíduo Satisfaz Restrição");
        jRadioButton_IndividualSatisfiesConstraint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_IndividualSatisfiesConstraintActionPerformed(evt);
            }
        });

        jRadioButton_ListTagValues.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jRadioButton_ListTagValues.setText("Listar Valores em Tag");
        jRadioButton_ListTagValues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ListTagValuesActionPerformed(evt);
            }
        });

        jRadioButton_ListIndividualTags.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jRadioButton_ListIndividualTags.setText("Listar Tags de Indivíduo");
        jRadioButton_ListIndividualTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ListIndividualTagsActionPerformed(evt);
            }
        });

        jRadioButton_ListIndividualsByConstraint.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jRadioButton_ListIndividualsByConstraint.setText("Listar Indivíduos por Restrição");
        jRadioButton_ListIndividualsByConstraint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ListIndividualsByConstraintActionPerformed(evt);
            }
        });

        jRadioButton_ListIndividualHierarchy.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jRadioButton_ListIndividualHierarchy.setText("Listar Hierarquia de Indivíduo");
        jRadioButton_ListIndividualHierarchy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ListIndividualHierarchyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_FunctionsLayout = new javax.swing.GroupLayout(jPanel_Functions);
        jPanel_Functions.setLayout(jPanel_FunctionsLayout);
        jPanel_FunctionsLayout.setHorizontalGroup(
            jPanel_FunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FunctionsLayout.createSequentialGroup()
                .addGroup(jPanel_FunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_ModelCheck)
                    .addComponent(jRadioButton_IndividualSatisfiesConstraint)
                    .addComponent(jRadioButton_ListTagValues)
                    .addComponent(jRadioButton_ListIndividualTags)
                    .addComponent(jRadioButton_ListIndividualsByConstraint)
                    .addComponent(jRadioButton_ListIndividualHierarchy))
                .addGap(0, 149, Short.MAX_VALUE))
        );
        jPanel_FunctionsLayout.setVerticalGroup(
            jPanel_FunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_FunctionsLayout.createSequentialGroup()
                .addComponent(jRadioButton_ModelCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_ListIndividualTags)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_ListIndividualHierarchy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_ListIndividualsByConstraint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_IndividualSatisfiesConstraint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_ListTagValues)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Parameters.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Parâmetros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N

        jTextField_ConstraintTag1.setEditable(false);

        jLabel_RequiredTag.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel_RequiredTag.setText("Tag Restrição 1:");

        jLabel_RequiredTagValue.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel_RequiredTagValue.setText("Valor:");

        jTextField_ConstraintValue1.setEditable(false);

        jLabel_TargetTag.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel_TargetTag.setText("Tag Restrição 2:");

        jTextField_ConstraintTag2.setEditable(false);

        jLabel_TargetTagValue.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel_TargetTagValue.setText("Valor:");

        jTextField_ConstraintValue2.setEditable(false);

        jLabel_IndividualID.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel_IndividualID.setText("ID Indivíduo:");

        jTextField_IndividualID.setEditable(false);

        jLabel_TargetTag1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel_TargetTag1.setText("Tag Alvo:");

        jTextField_TargetTag.setEditable(false);

        jLabel_RequiredTagValue1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel_RequiredTagValue1.setText("Tag:");

        jTextField_IndividualIdTag.setEditable(false);

        javax.swing.GroupLayout jPanel_ParametersLayout = new javax.swing.GroupLayout(jPanel_Parameters);
        jPanel_Parameters.setLayout(jPanel_ParametersLayout);
        jPanel_ParametersLayout.setHorizontalGroup(
            jPanel_ParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ParametersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_TargetTag1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_IndividualID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_RequiredTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_TargetTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_ConstraintTag2)
                    .addComponent(jTextField_IndividualID)
                    .addComponent(jTextField_ConstraintTag1)
                    .addComponent(jTextField_TargetTag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_ParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_ParametersLayout.createSequentialGroup()
                        .addComponent(jLabel_RequiredTagValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ConstraintValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_ParametersLayout.createSequentialGroup()
                        .addComponent(jLabel_TargetTagValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ConstraintValue2))
                    .addGroup(jPanel_ParametersLayout.createSequentialGroup()
                        .addComponent(jLabel_RequiredTagValue1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_IndividualIdTag, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_ParametersLayout.setVerticalGroup(
            jPanel_ParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ParametersLayout.createSequentialGroup()
                .addGroup(jPanel_ParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_IndividualID)
                    .addComponent(jTextField_IndividualID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_RequiredTagValue1)
                    .addComponent(jTextField_IndividualIdTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_RequiredTag)
                    .addComponent(jTextField_ConstraintTag1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_RequiredTagValue)
                    .addComponent(jTextField_ConstraintValue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TargetTag)
                    .addComponent(jTextField_ConstraintTag2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_TargetTagValue)
                    .addComponent(jTextField_ConstraintValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_TargetTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_TargetTag1))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jPanel_Description.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Descrição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N

        jTextArea_Description.setEditable(false);
        jTextArea_Description.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jTextArea_Description.setColumns(20);
        jTextArea_Description.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Description);

        jButton_Run.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Run.setText("Executar");
        jButton_Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_DescriptionLayout = new javax.swing.GroupLayout(jPanel_Description);
        jPanel_Description.setLayout(jPanel_DescriptionLayout);
        jPanel_DescriptionLayout.setHorizontalGroup(
            jPanel_DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DescriptionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_Run))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
        );
        jPanel_DescriptionLayout.setVerticalGroup(
            jPanel_DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DescriptionLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Run, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jPanel_Results.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N

        jTextArea_Results.setEditable(false);
        jTextArea_Results.setColumns(20);
        jTextArea_Results.setRows(5);
        jScrollPane_Results.setViewportView(jTextArea_Results);

        javax.swing.GroupLayout jPanel_ResultsLayout = new javax.swing.GroupLayout(jPanel_Results);
        jPanel_Results.setLayout(jPanel_ResultsLayout);
        jPanel_ResultsLayout.setHorizontalGroup(
            jPanel_ResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ResultsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane_Results, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_ResultsLayout.setVerticalGroup(
            jPanel_ResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_Results)
        );

        jPanel_Proofs.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 204, 204), new java.awt.Color(153, 0, 0)), "Provas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 11), new java.awt.Color(153, 0, 0))); // NOI18N

        jRadioButton_Proof1a.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jRadioButton_Proof1a.setText("Prova 1-a");
        jRadioButton_Proof1a.setEnabled(false);
        jRadioButton_Proof1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_Proof1aActionPerformed(evt);
            }
        });

        jRadioButton_Proof1b.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jRadioButton_Proof1b.setText("Prova 1-b");
        jRadioButton_Proof1b.setEnabled(false);
        jRadioButton_Proof1b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_Proof1bActionPerformed(evt);
            }
        });

        jRadioButton_Proof2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jRadioButton_Proof2.setText("Prova 2");
        jRadioButton_Proof2.setEnabled(false);
        jRadioButton_Proof2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_Proof2ActionPerformed(evt);
            }
        });

        jRadioButton_Proof3a.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jRadioButton_Proof3a.setText("Prova 3-a");
        jRadioButton_Proof3a.setEnabled(false);
        jRadioButton_Proof3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_Proof3aActionPerformed(evt);
            }
        });

        jRadioButton_Proof3b.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jRadioButton_Proof3b.setText("Prova 3-b");
        jRadioButton_Proof3b.setEnabled(false);
        jRadioButton_Proof3b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_Proof3bActionPerformed(evt);
            }
        });

        jRadioButton_Proof4.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jRadioButton_Proof4.setText("Prova 4");
        jRadioButton_Proof4.setEnabled(false);
        jRadioButton_Proof4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_Proof4ActionPerformed(evt);
            }
        });

        jRadioButton_Proof5.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jRadioButton_Proof5.setText("Prova 5");
        jRadioButton_Proof5.setEnabled(false);
        jRadioButton_Proof5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_Proof5ActionPerformed(evt);
            }
        });

        jRadioButton_Proof6a.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jRadioButton_Proof6a.setText("Prova 6-a");
        jRadioButton_Proof6a.setEnabled(false);
        jRadioButton_Proof6a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_Proof6aActionPerformed(evt);
            }
        });

        jRadioButton_Proof6b.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jRadioButton_Proof6b.setText("Prova6-b");
        jRadioButton_Proof6b.setEnabled(false);
        jRadioButton_Proof6b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_Proof6bActionPerformed(evt);
            }
        });

        jCheckBox_ActivateProofs.setText("Ativar Provas");
        jCheckBox_ActivateProofs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ActivateProofsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ProofsLayout = new javax.swing.GroupLayout(jPanel_Proofs);
        jPanel_Proofs.setLayout(jPanel_ProofsLayout);
        jPanel_ProofsLayout.setHorizontalGroup(
            jPanel_ProofsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ProofsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ProofsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ProofsLayout.createSequentialGroup()
                        .addGroup(jPanel_ProofsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_ProofsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jRadioButton_Proof2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton_Proof1a, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton_Proof1b, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel_ProofsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jRadioButton_Proof3b, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                .addComponent(jRadioButton_Proof3a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton_Proof4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_ProofsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButton_Proof5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton_Proof6a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton_Proof6b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jCheckBox_ActivateProofs))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel_ProofsLayout.setVerticalGroup(
            jPanel_ProofsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ProofsLayout.createSequentialGroup()
                .addGroup(jPanel_ProofsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ProofsLayout.createSequentialGroup()
                        .addComponent(jCheckBox_ActivateProofs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(jPanel_ProofsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_ProofsLayout.createSequentialGroup()
                                .addComponent(jRadioButton_Proof1a)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton_Proof1b)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton_Proof2))
                            .addGroup(jPanel_ProofsLayout.createSequentialGroup()
                                .addComponent(jRadioButton_Proof5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton_Proof6a)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton_Proof6b)))
                        .addGap(70, 70, 70))
                    .addGroup(jPanel_ProofsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jRadioButton_Proof3a)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_Proof3b)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_Proof4)
                .addContainerGap())
        );

        jPanel_ProofTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));

        jLabel_ProofTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        jLabel_ProofTitle.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_ProofTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel_ProofTitleLayout = new javax.swing.GroupLayout(jPanel_ProofTitle);
        jPanel_ProofTitle.setLayout(jPanel_ProofTitleLayout);
        jPanel_ProofTitleLayout.setHorizontalGroup(
            jPanel_ProofTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_ProofTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_ProofTitleLayout.setVerticalGroup(
            jPanel_ProofTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_ProofTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_ProgramPanelLayout = new javax.swing.GroupLayout(jPanel_ProgramPanel);
        jPanel_ProgramPanel.setLayout(jPanel_ProgramPanelLayout);
        jPanel_ProgramPanelLayout.setHorizontalGroup(
            jPanel_ProgramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ProgramPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ProgramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ProgramPanelLayout.createSequentialGroup()
                        .addComponent(jPanel_Stripe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_Stripe6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ProgramPanelLayout.createSequentialGroup()
                        .addGroup(jPanel_ProgramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_ProgramPanelLayout.createSequentialGroup()
                                .addGroup(jPanel_ProgramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel_Functions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel_Parameters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_ProgramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel_Description, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel_Proofs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jPanel_LoadModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_ProgramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel_Results, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_ProofTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel_ProgramPanelLayout.setVerticalGroup(
            jPanel_ProgramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ProgramPanelLayout.createSequentialGroup()
                .addGroup(jPanel_ProgramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_ProgramPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_ProgramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_Stripe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel_Stripe6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ProgramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_LoadModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_ProofTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ProgramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ProgramPanelLayout.createSequentialGroup()
                        .addGroup(jPanel_ProgramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel_Description, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_Functions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_ProgramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_Parameters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_Proofs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel_Results, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLayeredPane1.setLayer(jPanel_StartScreen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel_ProgramPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_StartScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_ProgramPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_StartScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_ProgramPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_LoadModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoadModelActionPerformed
        this.loadModel();
    }//GEN-LAST:event_jButton_LoadModelActionPerformed

    private void jButton_RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RunActionPerformed
        this.run();
    }//GEN-LAST:event_jButton_RunActionPerformed

    private void jRadioButton_ModelCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ModelCheckActionPerformed
        this.changeField(jTextField_ConstraintTag1, false, "");
        this.changeField(jTextField_ConstraintValue1, false, "");
        this.changeField(jTextField_ConstraintTag2, false, "");
        this.changeField(jTextField_ConstraintValue2, false, "");
        this.changeField(jTextField_TargetTag, false, "");
        this.changeField(jTextField_IndividualID, false, "");
        this.changeField(jTextField_IndividualIdTag, false, "");
        this.selectedFunction = 1; //Set the function to 1
        this.jTextArea_Description.setForeground(new java.awt.Color(0, 0, 0));
        this.jTextArea_Description.setText(
                "Verifica a validade do\n"
                + "modelo carregado.");
        this.run();
    }//GEN-LAST:event_jRadioButton_ModelCheckActionPerformed

    private void jRadioButton_IndividualSatisfiesConstraintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_IndividualSatisfiesConstraintActionPerformed
        this.changeField(jTextField_ConstraintTag1, true, null);
        this.changeField(jTextField_ConstraintValue1, true, null);
        this.changeField(jTextField_ConstraintTag2, true, null);
        this.changeField(jTextField_ConstraintValue2, true, null);
        this.changeField(jTextField_TargetTag, false, "");
        this.changeField(jTextField_IndividualID, true, null);
        this.changeField(jTextField_IndividualIdTag, true, null);
        this.selectedFunction = 5; //Set the function to 5
        this.jTextArea_Description.setForeground(new java.awt.Color(0, 0, 0));
        this.jTextArea_Description.setText(
                "Verifica se um dado\n"
                + "indivíduo satisfaz as\n"
                + "restrições sobre suas\n"
                + "Tags.");
    }//GEN-LAST:event_jRadioButton_IndividualSatisfiesConstraintActionPerformed

    private void jRadioButton_ListTagValuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ListTagValuesActionPerformed
        this.changeField(jTextField_ConstraintTag1, true, null);
        this.changeField(jTextField_ConstraintValue1, true, null);
        this.changeField(jTextField_ConstraintTag2, true, null);
        this.changeField(jTextField_ConstraintValue2, true, null);
        this.changeField(jTextField_TargetTag, true, null);
        this.changeField(jTextField_IndividualID, false, "");
        this.changeField(jTextField_IndividualIdTag, false, "");
        this.selectedFunction = 6; //Set the function to 6
        this.jTextArea_Description.setForeground(new java.awt.Color(0, 0, 0));
        this.jTextArea_Description.setText(
                "Lista todos os valores\n"
                + "encontrados na tag\n"
                + "alvo nos indivíduos\n"
                + "que satisfazem as\n"
                + "tags de restrição.");
    }//GEN-LAST:event_jRadioButton_ListTagValuesActionPerformed

    private void jRadioButton_ListIndividualTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ListIndividualTagsActionPerformed
        this.changeField(jTextField_ConstraintTag1, false, "");
        this.changeField(jTextField_ConstraintValue1, false, "");
        this.changeField(jTextField_ConstraintTag2, false, "");
        this.changeField(jTextField_ConstraintValue2, false, "");
        this.changeField(jTextField_TargetTag, false, "");
        this.changeField(jTextField_IndividualID, true, null);
        this.changeField(jTextField_IndividualIdTag, true, null);
        this.selectedFunction = 2; //Set the function to 2
        this.jTextArea_Description.setForeground(new java.awt.Color(0, 0, 0));
        this.jTextArea_Description.setText(
                "Lista todas as tags\n"
                + "de um determinado\n"
                + "indivíduo.");
    }//GEN-LAST:event_jRadioButton_ListIndividualTagsActionPerformed

    private void jRadioButton_ListIndividualsByConstraintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ListIndividualsByConstraintActionPerformed
        this.changeField(jTextField_ConstraintTag1, true, null);
        this.changeField(jTextField_ConstraintValue1, true, null);
        this.changeField(jTextField_ConstraintTag2, true, null);
        this.changeField(jTextField_ConstraintValue2, true, null);
        this.changeField(jTextField_TargetTag, false, "");
        this.changeField(jTextField_IndividualID, false, "");
        this.changeField(jTextField_IndividualIdTag, false, "");
        this.selectedFunction = 4; //Set the function to 4
        this.jTextArea_Description.setForeground(new java.awt.Color(0, 0, 0));
        this.jTextArea_Description.setText(
                "Lista todos os\n"
                + "indivíduos que\n"
                + "satisfazem as\n"
                + "restrições de tag.");
    }//GEN-LAST:event_jRadioButton_ListIndividualsByConstraintActionPerformed

    private void jRadioButton_ListIndividualHierarchyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ListIndividualHierarchyActionPerformed
        this.changeField(jTextField_ConstraintTag1, false, "");
        this.changeField(jTextField_ConstraintValue1, false, "");
        this.changeField(jTextField_ConstraintTag2, false, "");
        this.changeField(jTextField_ConstraintValue2, false, "");
        this.changeField(jTextField_TargetTag, false, "");
        this.changeField(jTextField_IndividualID, true, null);
        this.changeField(jTextField_IndividualIdTag, true, null);
        this.selectedFunction = 3; //Set the function to 3
        this.jTextArea_Description.setForeground(new java.awt.Color(0, 0, 0));
        this.jTextArea_Description.setText(
                "Lista a hierarquia\n"
                + "à qual um indivíduo\n"
                + "pertence.");
    }//GEN-LAST:event_jRadioButton_ListIndividualHierarchyActionPerformed

    private void jRadioButton_Proof1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Proof1aActionPerformed
        this.jTextField_ModelFile.setText("produto_prova1a.xml");
        this.loadModel();
        this.jLabel_ProofTitle.setText("Classificação - Vestidos Pertencem a Moda Feminina");
        this.jRadioButton_ListTagValuesActionPerformed(evt);
        this.jTextField_ConstraintTag1.setText("categoria");
        this.jTextField_ConstraintValue1.setText("vestido");
        this.jTextField_ConstraintTag2.setText("");
        this.jTextField_ConstraintValue2.setText("");
        this.jTextField_TargetTag.setText("classificacao");
        this.jTextArea_Description.setForeground(new java.awt.Color(204, 0, 0));
        this.jTextArea_Description.setText(
                "Mostrar que as \n"
                + "categorias encontradas\n"
                + "em vestido são moda\n"
                + "feminina,\n"
                + "mas por asserção.");
        
        String result = controlClass.createProof("1a", this.jTextField_ModelFile.getText());
        jTextArea_Results.setText("Valores encontrados na Tag Classificacao onde a Tag Categoria = Vestido:\n\n");
        jTextArea_Results.append(result);
    }//GEN-LAST:event_jRadioButton_Proof1aActionPerformed

    private void jRadioButton_Proof1bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Proof1bActionPerformed
        this.jTextField_ModelFile.setText("produto_prova1b.xml");
        this.loadModel();
        this.jLabel_ProofTitle.setText("Classificação - Vestidos Não Pertencem a Moda Feminina");
        this.jRadioButton_ListTagValuesActionPerformed(evt);
        this.jRadioButton_ListTagValues.setSelected(true);
        this.jTextField_ConstraintTag1.setText("categoria");
        this.jTextField_ConstraintValue1.setText("vestido");
        this.jTextField_ConstraintTag2.setText("");
        this.jTextField_ConstraintValue2.setText("");
        this.jTextField_TargetTag.setText("classificacao");
        this.jTextArea_Description.setForeground(new java.awt.Color(204, 0, 0));
        this.jTextArea_Description.setText(
                "Mostrar que, por não\n"
                + "ser asserido, nenhum\n"
                + "vestido foi classificado\n"
                + "como moda feminina.");
        
        String result = controlClass.createProof("1b", this.jTextField_ModelFile.getText());
        jTextArea_Results.setText("Valores encontrados na Tag Classificacao onde a Tag Categoria = Vestido:\n\n");
        jTextArea_Results.append(result);
    }//GEN-LAST:event_jRadioButton_Proof1bActionPerformed

    private void jRadioButton_Proof2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Proof2ActionPerformed
        this.jTextField_ModelFile.setText("produto_prova2.xml");
        this.loadModel();
        this.jLabel_ProofTitle.setText("Validação de Instâncias – Calça Plus Size");
        this.jRadioButton_IndividualSatisfiesConstraintActionPerformed(evt);
        this.jRadioButton_IndividualSatisfiesConstraint.setSelected(true);
        this.jTextField_ConstraintTag1.setText("categoria");
        this.jTextField_ConstraintValue1.setText("calca");
        this.jTextField_ConstraintTag2.setText("plus_size");
        this.jTextField_ConstraintValue2.setText("sim");
        this.jTextField_IndividualID.setText("1200827");
        this.jTextArea_Description.setForeground(new java.awt.Color(204, 0, 0));
        this.jTextArea_Description.setText(
                "Mostrar que uma calça\n"
                + "será dita tendo tamanho\n"
                + "plus size, mas somente\n"
                + "porque isto foi\n"
                + "asserido.");
        
        String result = controlClass.createProof("2", this.jTextField_ModelFile.getText());
        jTextArea_Results.setText("Indivíduo identificado por 1200827 satisfaz as condições:\n\n");
        jTextArea_Results.append(result);
    }//GEN-LAST:event_jRadioButton_Proof2ActionPerformed

    private void jRadioButton_Proof3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Proof3aActionPerformed
        this.jTextField_ModelFile.setText("produto_prova3a.xml");
        this.loadModel();
        this.jLabel_ProofTitle.setText("Inconsistência de Asserções");
        this.jRadioButton_ModelCheckActionPerformed(evt);
        this.jRadioButton_ModelCheck.setSelected(true);
        this.jTextArea_Description.setForeground(new java.awt.Color(204, 0, 0));
        this.jTextArea_Description.setText(
                "Mostrar que um produto\n"
                + "pode ter uma quantidade\n"
                + "de preenchimentos\n"
                + "inconsistentes com\n"
                + "o asserido.");
    }//GEN-LAST:event_jRadioButton_Proof3aActionPerformed

    private void jRadioButton_Proof3bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Proof3bActionPerformed
        this.jTextField_ModelFile.setText("produto_prova3b.xml");
        this.loadModel();
        this.jLabel_ProofTitle.setText("Inconsistência de Asserções");
        this.jRadioButton_ListIndividualTagsActionPerformed(evt);
        this.jRadioButton_ListIndividualTags.setSelected(true);
        this.jTextField_IndividualID.setText("1763822");
        this.jTextArea_Description.setForeground(new java.awt.Color(204, 0, 0));
        this.jTextArea_Description.setText(
                "Mostrar que um produto\n"
                + "pode ter uma quantidade\n"
                + "de preenchimentos\n"
                + "inconsistentes com\n"
                + "o asserido.");

        String result = controlClass.createProof("3b", this.jTextField_ModelFile.getText());
        jTextArea_Results.append(result);
    }//GEN-LAST:event_jRadioButton_Proof3bActionPerformed

    private void jRadioButton_Proof4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Proof4ActionPerformed
        this.jTextField_ModelFile.setText("produto_prova4.xml");
        this.loadModel();
        this.jLabel_ProofTitle.setText("Realização – Hierarquia de Indivíduo");
        this.jRadioButton_ListIndividualHierarchyActionPerformed(evt);
        this.jRadioButton_ListIndividualHierarchy.setSelected(true);
        this.jTextField_IndividualID.setText("1246194");
        this.jTextArea_Description.setForeground(new java.awt.Color(204, 0, 0));
        this.jTextArea_Description.setText(
                "Mostrar a forma de\n"
                + "identificação de\n"
                + "conceitos de um\n"
                + "indivíduo a partir\n"
                + "de hierarquia.");
        
        String result = controlClass.createProof("4", this.jTextField_ModelFile.getText());
        jTextArea_Results.append(result);
    }//GEN-LAST:event_jRadioButton_Proof4ActionPerformed

    private void jRadioButton_Proof5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Proof5ActionPerformed
        this.jTextField_ModelFile.setText("produto_prova5.xml");
        this.loadModel();
        this.jLabel_ProofTitle.setText("Recuperação – Listar Indivíduos de Conceito");
        this.jRadioButton_ListIndividualsByConstraintActionPerformed(evt);
        this.jRadioButton_ListIndividualsByConstraint.setSelected(true);
        this.jTextField_ConstraintTag1.setText("categoria");
        this.jTextField_ConstraintValue1.setText("calca");
        this.jTextField_ConstraintTag2.setText("plus_size");
        this.jTextField_ConstraintValue2.setText("sim");
        this.jTextArea_Description.setForeground(new java.awt.Color(204, 0, 0));
        this.jTextArea_Description.setText(
                "Mostrar que indivíduos\n"
                + "só poderão ser listados\n"
                + "dentro de determinado\n"
                + "conceito se isto for\n"
                + "asserido.");
        
        String result = controlClass.createProof("5", this.jTextField_ModelFile.getText());
        jTextArea_Results.setText("Indivíduos que satisfazem as restrições:\nCategoria = Calça\nPlusSize = Sim\n");
        jTextArea_Results.append(result);
    }//GEN-LAST:event_jRadioButton_Proof5ActionPerformed

    private void jRadioButton_Proof6aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Proof6aActionPerformed
        //Uses the same model than 1a
        this.jTextField_ModelFile.setText("produto_prova1a.xml");
        this.loadModel();
        this.jLabel_ProofTitle.setText("Diminuição da Ambiguidade – Listar Indivíduos Tamanho L");
        this.jRadioButton_ListIndividualsByConstraintActionPerformed(evt);
        this.jRadioButton_ListIndividualsByConstraint.setSelected(true);
        this.jTextField_ConstraintTag1.setText("categoria");
        this.jTextField_ConstraintValue1.setText("blusa");
        this.jTextField_ConstraintTag2.setText("tamanho");
        this.jTextField_ConstraintValue2.setText("l");
        this.jTextArea_Description.setForeground(new java.awt.Color(204, 0, 0));
        this.jTextArea_Description.setText(
                "Mostrar a falta de\n"
                + "relações de \n"
                + "equivalência do modelo\n"
                + "não semântico.");

        String result = controlClass.createProof("6a", this.jTextField_ModelFile.getText());
        jTextArea_Results.setText("Indivíduos que satisfazem as restrições:\nCategoria = Blusa\nTamanho = L\n");
        jTextArea_Results.append(result);
    }//GEN-LAST:event_jRadioButton_Proof6aActionPerformed

    private void jRadioButton_Proof6bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Proof6bActionPerformed
        this.jTextField_ModelFile.setText("produto_prova1a.xml");
        this.loadModel();
        this.jLabel_ProofTitle.setText("Diminuição da Ambiguidade – Listar Indivíduos Tamanho G");
        this.jRadioButton_ListIndividualsByConstraintActionPerformed(evt);
        this.jRadioButton_ListIndividualsByConstraint.setSelected(true);
        this.jTextField_ConstraintTag1.setText("categoria");
        this.jTextField_ConstraintValue1.setText("blusa");
        this.jTextField_ConstraintTag2.setText("tamanho");
        this.jTextField_ConstraintValue2.setText("g");
        this.jTextArea_Description.setText(
                "Mostrar a falta de\n"
                + "relações de \n"
                + "equivalência do modelo\n"
                + "não semântico.");
        
        String result = controlClass.createProof("6b", this.jTextField_ModelFile.getText());
        jTextArea_Results.setText("Indivíduos que satisfazem as restrições:\nCategoria = Blusa\nTamanho = G\n");
        jTextArea_Results.append(result);
    }//GEN-LAST:event_jRadioButton_Proof6bActionPerformed

    private void jCheckBox_ActivateProofsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ActivateProofsActionPerformed
        this.jTextArea_Description.setText("");
        this.jLabel_ProofTitle.setText("");
        jTextArea_Results.setLineWrap(true);
        jTextArea_Results.setWrapStyleWord(true);
        if (this.jCheckBox_ActivateProofs.isSelected()) {
            activateProofButtons(true);
            activateFunctionButtons(false);
        } else {
            activateProofButtons(false);
            activateFunctionButtons(true);
        }
    }//GEN-LAST:event_jCheckBox_ActivateProofsActionPerformed

    //Method that changes the screen when clicked on the icon image
    private void jLabel_LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LogoMouseClicked
        this.jLayeredPane1.moveToFront(jPanel_ProgramPanel);
    }//GEN-LAST:event_jLabel_LogoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_Functions;
    private javax.swing.ButtonGroup buttonGroup_Proofs;
    private javax.swing.JButton jButton_LoadModel;
    private javax.swing.JButton jButton_Run;
    private javax.swing.JCheckBox jCheckBox_ActivateProofs;
    private javax.swing.JLabel jLabel_ClickToStart;
    private javax.swing.JLabel jLabel_IndividualID;
    private javax.swing.JLabel jLabel_LoadFileOutput;
    private javax.swing.JLabel jLabel_Logo;
    private javax.swing.JLabel jLabel_ModelFile;
    private javax.swing.JLabel jLabel_ProofTitle;
    private javax.swing.JLabel jLabel_RequiredTag;
    private javax.swing.JLabel jLabel_RequiredTagValue;
    private javax.swing.JLabel jLabel_RequiredTagValue1;
    private javax.swing.JLabel jLabel_TargetTag;
    private javax.swing.JLabel jLabel_TargetTag1;
    private javax.swing.JLabel jLabel_TargetTagValue;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JLabel jLabel_VersionName;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel_Description;
    private javax.swing.JPanel jPanel_Functions;
    private javax.swing.JPanel jPanel_LoadModel;
    private javax.swing.JPanel jPanel_Parameters;
    private javax.swing.JPanel jPanel_ProgramPanel;
    private javax.swing.JPanel jPanel_ProofTitle;
    private javax.swing.JPanel jPanel_Proofs;
    private javax.swing.JPanel jPanel_Results;
    private javax.swing.JPanel jPanel_StartScreen;
    private javax.swing.JPanel jPanel_Stripe1;
    private javax.swing.JPanel jPanel_Stripe6;
    private javax.swing.JRadioButton jRadioButton_IndividualSatisfiesConstraint;
    private javax.swing.JRadioButton jRadioButton_ListIndividualHierarchy;
    private javax.swing.JRadioButton jRadioButton_ListIndividualTags;
    private javax.swing.JRadioButton jRadioButton_ListIndividualsByConstraint;
    private javax.swing.JRadioButton jRadioButton_ListTagValues;
    private javax.swing.JRadioButton jRadioButton_ModelCheck;
    private javax.swing.JRadioButton jRadioButton_Proof1a;
    private javax.swing.JRadioButton jRadioButton_Proof1b;
    private javax.swing.JRadioButton jRadioButton_Proof2;
    private javax.swing.JRadioButton jRadioButton_Proof3a;
    private javax.swing.JRadioButton jRadioButton_Proof3b;
    private javax.swing.JRadioButton jRadioButton_Proof4;
    private javax.swing.JRadioButton jRadioButton_Proof5;
    private javax.swing.JRadioButton jRadioButton_Proof6a;
    private javax.swing.JRadioButton jRadioButton_Proof6b;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane_Results;
    private javax.swing.JTextArea jTextArea_Description;
    private javax.swing.JTextArea jTextArea_Results;
    private javax.swing.JTextField jTextField_ConstraintTag1;
    private javax.swing.JTextField jTextField_ConstraintTag2;
    private javax.swing.JTextField jTextField_ConstraintValue1;
    private javax.swing.JTextField jTextField_ConstraintValue2;
    private javax.swing.JTextField jTextField_IndividualID;
    private javax.swing.JTextField jTextField_IndividualIdTag;
    private javax.swing.JTextField jTextField_ModelFile;
    private javax.swing.JTextField jTextField_TargetTag;
    // End of variables declaration//GEN-END:variables

    //Method that sets an incon to the jFrame 
    private void setIcon() {
        String icon_path = "terminus_xml_small.png";
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource(icon_path)));
    }

    //Method that sets the current system look and feel
    private void setLookAndFeel() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException e) {
            System.out.println("Não foi possível encontrar o Look and Feel especificado!");
        }

    }

    //Method that shows the sucess model load output message
    private void loadModelSucess() {
        this.jLabel_LoadFileOutput.setForeground(new java.awt.Color(0, 204, 0));
        this.jLabel_LoadFileOutput.setText("Modelo carregado!");
    }

    //Method that shows the fail model load output message
    private void loadModelFail() {
        this.jLabel_LoadFileOutput.setForeground(new java.awt.Color(204, 0, 0));
        this.jLabel_LoadFileOutput.setText("Modelo não carregado!");
    }

    //This method change a determined field to editable or not and change also the text in this field
    private void changeField(JTextField field, boolean editable, String text) {
        field.setEditable(editable);
        if (text != null) {
            field.setText(text);
        }
    }

    //This method activates or desactivates the Proofs buttons
    private void activateProofButtons(boolean active) {
        Enumeration<AbstractButton> buttonList;
        AbstractButton button;

        buttonList = buttonGroup_Proofs.getElements();
        while (buttonList.hasMoreElements()) {
            button = buttonList.nextElement();
            button.setEnabled(active);
        }
    }

    //This method activates or desactivates the Function buttons
    private void activateFunctionButtons(boolean active) {
        Enumeration<AbstractButton> buttonList;
        AbstractButton button;

        buttonList = buttonGroup_Functions.getElements();
        while (buttonList.hasMoreElements()) {
            button = buttonList.nextElement();
            button.setEnabled(active);
        }
    }

    //Method that loads the XML model as well as the XSD schema
    private void loadModel() {
        String nomeArquivo = jTextField_ModelFile.getText();
        OpenFile openFile = new OpenFile();
        docXml = openFile.createDoc(nomeArquivo);
        if (docXml != null) {
            loadModelSucess();
        } else {
            loadModelFail();
        }
    }

    //Method that runs a specific function defined by the 
    private void run() {
        String result = "";
        switch (selectedFunction){
            case 0: //No function is selected
                result = "Nenhuma função foi selecionada!";
                break;
            case 1: //Model Check function
                result = validatesModel();
                break;
            case 2: //List Individual Tags function
                result = controlClass.listIndividualTags(jTextField_ModelFile.getText(), jTextField_IndividualIdTag.getText(), jTextField_IndividualID.getText());
                break;
            case 3: //List Individual Hierarchy function
                result = controlClass.listIndividualHierarchy(jTextField_ModelFile.getText(), jTextField_IndividualIdTag.getText(), jTextField_IndividualID.getText());
                break;
            case 4: //List Individuals By Constraint function
                result = controlClass.listIndividualsByRestriction(jTextField_ModelFile.getText(),
                        jTextField_ConstraintTag1.getText(), jTextField_ConstraintTag2.getText(),
                        jTextField_ConstraintValue1.getText(), jTextField_ConstraintValue2.getText());
                break;
            case 5: //Individual Satisfies Constraint function
                result = controlClass.individualSatisfiesRestriction(jTextField_ModelFile.getText(),
                        jTextField_IndividualID.getText(), jTextField_IndividualIdTag.getText(),
                        jTextField_ConstraintTag1.getText(), jTextField_ConstraintValue1.getText(),
                        jTextField_ConstraintTag2.getText(), jTextField_ConstraintValue2.getText());
                break;
            case 6: //List Tag Values function
                break;
        }
        this.jTextArea_Results.setText(result);
    }
    
    //Validates model and return
    private String validatesModel() {
        String xmlFileName = jTextField_ModelFile.getText();
        boolean isValid = false;
        
        if (xmlFileName.contains("produto_prova1")) {
            xsdFileName = "produto_prova1.xsd";
            isValid = Validates.validateModel(xmlFileName, xsdFileName);
        } else if (xmlFileName.contains("produto_prova2")) {
            xsdFileName = "produto_prova2.xsd";
            isValid = Validates.validateModel(xmlFileName, xsdFileName);
        } else if (xmlFileName.contains("produto_prova3")) {
            xsdFileName = "produto_prova3.xsd";
            isValid = Validates.validateModel(xmlFileName, xsdFileName);
        } else if (xmlFileName.contains("produto_prova4")) {
            xsdFileName = "produto_prova4.xsd";
            isValid = Validates.validateModel(xmlFileName, xsdFileName);
        } else if (xmlFileName.contains("produto_prova5")) {
            xsdFileName = "produto_prova5.xsd";
            isValid = Validates.validateModel(xmlFileName, xsdFileName);
        } else {
            String[] xsdFileSplit = xmlFileName.split(".xml");
            xsdFileName = xsdFileSplit[0].concat(".xsd");
            isValid = Validates.validateModel(xmlFileName, xsdFileName);
        }
        
        if (isValid) {
            return "Modelo válido!";
        } else {
            return "Modelo inválido!";
        }
    }
}
